import { build as esbuildBuild, context } from 'esbuild';
import process from 'process';
import { copy } from 'esbuild-plugin-copy';
import path from 'node:path';

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Mark every Node builtin import as external so Obsidian Mobile WebView never tries
// to require missing builtins at runtime. Catches both `node:*` (modern) and bare names
// like `worker_threads`/`crypto` (legacy) from transitive LangChain dependencies.
// Maintained list mirrors `NODE_BUILTIN_NAMES` in scripts/audit-bundle.mjs.
const NODE_BUILTIN_BARE = /^(?:fs|path|child_process|os|crypto|stream|url|net|tls|http|https|zlib|querystring|readline|buffer|events|util|tty|dns|module|process|worker_threads|fs\/promises|stream\/promises)$/;
const externalNodeBuiltinsPlugin = {
	name: "external-node-builtins",
	setup(build) {
		build.onResolve({ filter: /^node:/ }, (args) => ({ path: args.path, external: true }));
		build.onResolve({ filter: NODE_BUILTIN_BARE }, (args) => ({ path: args.path, external: true }));
	},
};

const inlineSqliteWorkerPlugin = {
	name: "inline-sqlite-worker",
	setup(build) {
		build.onResolve({ filter: /\?worker-source$/ }, (args) => {
			const sourcePath = args.path.replace(/\?worker-source$/, "");
			return {
				path: path.resolve(args.resolveDir, sourcePath),
				namespace: "sqlite-worker-source",
			};
		});

		build.onLoad({ filter: /.*/, namespace: "sqlite-worker-source" }, async (args) => {
			const result = await esbuildBuild({
				platform: "browser",
				mainFields: ["browser", "module", "main"],
				conditions: ["browser"],
				entryPoints: [args.path],
				bundle: true,
				format: "esm",
				target: "es2020",
				logLevel: "silent",
				write: false,
				metafile: true,
				minify: prod ? true : false,
				sourcemap: false,
				loader: {
					'.ts': 'ts',
					'.js': 'js',
					'.mjs': 'js',
				},
				define: {
					"process.env.NODE_ENV": prod ? '"production"' : '"development"',
				},
			});
			return {
				contents: `export default ${JSON.stringify(result.outputFiles[0].text)};`,
				loader: "js",
				watchFiles: Object.keys(result.metafile.inputs),
			};
		});
	},
};

const mainContext = await context({
	platform: "browser",
	mainFields: ["browser", "module", "main"],
	conditions: ["browser"],
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		// Mobile-compat note: ALL `node:*` builtins are additionally marked external via
		// the `externalNodeBuiltinsPlugin` below (esbuild's `external` field accepts only
		// strings; regex matching must be done in a plugin). Obsidian Mobile WebView throws
		// when these modules are required, so this is mobile compatibility, NOT size opt.
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr"],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "dist/main.js",
	minify: prod ? true : false,
	loader: {
		'.ts': 'ts',
		'.tsx': 'tsx',
		'.js': 'js',
		'.jsx': 'jsx',
		'.md': 'text',
		// `binary` (vs `dataurl`): bundle source is the same base64 payload either way (esbuild's
		// browser-target binary loader still encodes via base64), but `binary` decodes the
		// ~941KB SQLite wasm to a Uint8Array once at module load — sqlite-inline-assets caches
		// the resulting blob URL across all SqliteVectorIndex instances. The old `dataurl` path
		// kept a ~1.25MB string in memory permanently AND re-ran the atob+Blob conversion every
		// time SqliteVectorIndex was reconstructed. Trade-off: +333 bytes for the __toBinary
		// helper in exchange for ~1.25MB persistent heap + per-reconnect work.
		'.wasm': 'binary',
	},
	define: {
		"process.env.NODE_ENV": prod ? '"production"' : '"development"',
	},
	splitting: false,
	plugins: [
		copy({
			assets: [
				{
					from: ['./manifest.json'],
					to: ['manifest.json'],
				},
				{
					from: ['./manifest-beta.json'],
					to: ['manifest-beta.json'],
				},
				{
					from: ['./styles.css'],
					to: ['styles.css'],
				},
			],
		}),
		inlineSqliteWorkerPlugin,
		externalNodeBuiltinsPlugin,
	],
});

if (prod) {
	await mainContext.rebuild();
	process.exit(0);
} else {
	await mainContext.watch();
}
