import { build as esbuildBuild, context } from 'esbuild';
import process from 'process';
import { copy } from 'esbuild-plugin-copy';
import path from 'node:path';

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const inlineSqliteWorkerPlugin = {
	name: "inline-sqlite-worker",
	setup(build) {
		build.onResolve({ filter: /\?worker-source$/ }, (args) => {
			const sourcePath = args.path.replace(/\?worker-source$/, "");
			return {
				path: path.resolve(args.resolveDir, sourcePath),
				namespace: "sqlite-worker-source",
			};
		});

		build.onLoad({ filter: /.*/, namespace: "sqlite-worker-source" }, async (args) => {
			const result = await esbuildBuild({
				platform: "browser",
				mainFields: ["browser", "module", "main"],
				conditions: ["browser"],
				entryPoints: [args.path],
				bundle: true,
				format: "esm",
				target: "es2020",
				logLevel: "silent",
				write: false,
				metafile: true,
				minify: prod ? true : false,
				sourcemap: false,
				loader: {
					'.ts': 'ts',
					'.js': 'js',
					'.mjs': 'js',
				},
				define: {
					"process.env.NODE_ENV": prod ? '"production"' : '"development"',
				},
			});
			return {
				contents: `export default ${JSON.stringify(result.outputFiles[0].text)};`,
				loader: "js",
				watchFiles: Object.keys(result.metafile.inputs),
			};
		});
	},
};

const mainContext = await context({
	platform: "browser",
	mainFields: ["browser", "module", "main"],
	conditions: ["browser"],
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr"],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "dist/main.js",
	minify: prod ? true : false,
	loader: {
		'.ts': 'ts',
		'.tsx': 'tsx',
		'.js': 'js',
		'.jsx': 'jsx',
		'.md': 'text',
		'.wasm': 'dataurl',
	},
	define: {
		"process.env.NODE_ENV": prod ? '"production"' : '"development"',
	},
	splitting: false,
	plugins: [
		copy({
			assets: [
				{
					from: ['./manifest.json'],
					to: ['manifest.json'],
				},
				{
					from: ['./manifest-beta.json'],
					to: ['manifest-beta.json'],
				},
				{
					from: ['./styles.css'],
					to: ['styles.css'],
				},
			],
		}),
		inlineSqliteWorkerPlugin,
	],
});

if (prod) {
	await mainContext.rebuild();
	process.exit(0);
} else {
	await mainContext.watch();
}
