import { context } from 'esbuild';
import process from 'process';
import { copy } from 'esbuild-plugin-copy';

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const mainContext = await context({
	platform: "browser",
	mainFields: ["browser", "module", "main"],
	conditions: ["browser"],
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr"],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "dist/main.js",
	minify: prod ? true : false,
	loader: {
		'.ts': 'ts',
		'.tsx': 'tsx',
		'.js': 'js',
		'.jsx': 'jsx',
	},
	define: {
		"process.env.NODE_ENV": prod ? '"production"' : '"development"',
	},
	splitting: false,
	plugins: [
		copy({
			assets: [
				{
					from: ['./manifest.json'],
					to: ['manifest.json'],
				},
				{
					from: ['./manifest-beta.json'],
					to: ['manifest-beta.json'],
				},
				{
					from: ['./styles.css'],
					to: ['styles.css'],
				},
				{
					from: ['./node_modules/@sqliteai/sqlite-wasm/sqlite-wasm/jswasm/sqlite3.wasm'],
					to: ['sqlite3.wasm'],
				},
			],
		}),
	],
});

const workerContext = await context({
	platform: "browser",
	mainFields: ["browser", "module", "main"],
	conditions: ["browser"],
	entryPoints: ["src/vss/sqlite-worker.ts"],
	bundle: true,
	format: "esm",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	outfile: "dist/vss-sqlite-worker.js",
	minify: prod ? true : false,
	loader: {
		'.ts': 'ts',
		'.js': 'js',
		'.mjs': 'js',
	},
	define: {
		"process.env.NODE_ENV": prod ? '"production"' : '"development"',
	},
});

if (prod) {
	await Promise.all([
		mainContext.rebuild(),
		workerContext.rebuild(),
	]);
	process.exit(0);
} else {
	await Promise.all([
		mainContext.watch(),
		workerContext.watch(),
	]);
}
