/* Copyright 2023 edonyzpc */

/**
 * Pagelet (Review Assistant) v1 — public barrel.
 *
 * Track B1 surface only. Subsequent B-tasks (B2-B6) will add their own
 * exports here; keep this file thin and re-export only the types/values
 * downstream code (or Track C C1 wiring) is expected to consume.
 */

export {
    PageletReviewModel,
    reviewNote,
    type PageletChatModelFactory,
    type PageletChatModelLike,
    type PageletReviewDiagnostics,
    type PageletReviewErrorCode,
    type PageletReviewModelOptions,
    type PageletReviewOutcome,
    type PageletReviewPath,
    type PageletReviewProgressEvent,
    type PageletReviewProgressPhase,
    type PageletReviewTimingEntry,
} from "./pa-review-model";

export {
    FEW_SHOT_EN,
    FEW_SHOT_ZH,
    PAGELET_DEFAULT_TARGET_SUGGESTIONS,
    PAGELET_FIELD_LIMITS,
    PAGELET_LANGUAGE_CODES,
    PAGELET_SCHEMA_VERSION,
    PAGELET_SUGGESTION_KINDS,
    PAGELET_SYSTEM_PROMPT_BASE,
    PageletReviewInputSchema,
    PageletReviewMetadataSchema,
    PageletReviewResultSchema,
    PageletSegmentSchema,
    PageletSuggestionSchema,
    PageletStructuredReviewResultSchema,
    PageletStructuredSuggestionSchema,
    buildJsonModeSchemaHint,
    buildSystemPrompt,
    buildUserPrompt,
    extractJsonPayload,
    filterSuggestionsBySourceIds,
    resolvePageletTargetSuggestionCount,
    summarizeZodIssues,
    tolerantJsonParse,
    truncateOverlongFields,
    type PageletLanguageCode,
    type PageletReviewInput,
    type PageletReviewMetadata,
    type PageletReviewResult,
    type PageletSegment,
    type PageletSuggestion,
    type PageletSuggestionKind,
    type PageletStructuredReviewResult,
    type SourceIdFilterResult,
    type TruncationResult,
} from "./pa-review-schemas";

export {
    PAGELET_DEFAULT_PRICING,
    PAGELET_TOKEN_LIMITS,
    PageletCostTracker,
    computeCost,
    estimateTokens,
    estimateTokensFor,
    formatUsd,
    lookupPricing,
    preCheckCost,
    pricingKey,
    type CostPreCheckDecision,
    type PageletCostBudget,
    type PageletCostEntry,
    type PageletCostRecordInput,
    type PageletCostSummary,
    type PageletCostTrackerOptions,
    type PageletPricingEntry,
} from "./pa-review-cost";

export {
    InMemoryRateLimitStorage,
    PAGELET_RATE_LIMIT_DEFAULTS,
    PageletRateLimiter,
    decide as decideRateLimit,
    prune as pruneRateLimitState,
    type PageletRateLimitConfig,
    type PageletRateLimitState,
    type PageletRateLimitStorage,
    type PageletRateLimiterOptions,
    type RateLimitDecision,
} from "./pa-review-rate-limit";

export {
    MAX_COLLISION_SUFFIX,
    PAGELET_DEFAULT_REVIEWS_FOLDER,
    PAGELET_FILENAME_INFIX,
    assembleReviewNote,
    buildReviewMetadata,
    formatPageletDate,
    formatPageletIsoTimestamp,
    mintNonCollidingReviewNotePath,
    normalizeReviewsFolder as normalizePageletReviewsFolder,
    renderReviewBody,
    resolveReviewNotePath,
    sanitizeSourceBaseName,
    serializeFrontmatter,
    writeReviewNote,
    type PageletReviewFileIOSettings,
    type PageletReviewIOAdapter,
    type PageletReviewVaultLike,
    type ResolveReviewNotePathInput,
    type WriteReviewNoteInput,
    type WriteReviewNoteResult,
} from "./pa-review-file-io";

export {
    PAGELET_APPROX_CHARS_PER_TOKEN,
    PAGELET_SCOPE_DEFAULT_MAX_INCLUDED,
    PAGELET_SEGMENT_TARGET_CHARS,
    applyPageletScopeToggle,
    buildPageletScopePlan,
    buildPageletScopeReviewBundle,
    rangeLabel,
    selectPageletScope,
    skippedReasonLabel,
    type BuildPageletScopePlanOptions,
    type BuildPageletScopeReviewBundleOptions,
    type PageletReviewRange,
    type PageletScopeCandidate,
    type PageletScopeCandidateReason,
    type PageletScopeFileLike,
    type PageletScopeMetadataLike,
    type PageletScopePlan,
    type PageletScopeReviewBundle,
    type PageletScopeSelection,
    type PageletScopeSkippedReason,
    type PageletScopeSourceReference,
} from "./scope";

// Track C · C1 — Write Action Framework v1 capability + runtime composer.
export {
    PAGELET_PROVIDER_ID,
    PAGELET_WRITE_REVIEW_OUTPUT_NAME,
    createPaReviewToolProvider,
    createPaReviewToolProviderForApp,
    type CreatePaReviewToolProviderOptions,
    type PageletReviewToolSettings,
    type PageletReviewToolVaultLike,
    type PageletWriteReviewOutputInput,
    type PaReviewToolProvider,
} from "./pa-review-tool-provider";

export {
    SELF_WRITE_WINDOW_MS as PAGELET_SELF_WRITE_WINDOW_MS,
    createPaReviewRuntime,
    type CreatePaReviewRuntimeOptions,
    type PaReviewPaAgentOptionsBundle,
    type PaReviewRuntime,
} from "./pa-review-runtime";

export {
    PAGELET_VIEW_TYPE,
    PageletView,
    type PageletPanelReviewData,
} from "./view";

// Track B · B5 compatibility / a11y surface — view-type gating,
// debounce + idempotency, ribbon registration, Cmd+/ focus command.
export {
    PAGELET_DATA_PLUGIN_VALUE,
    PAGELET_DEFAULT_DEBOUNCE_MS,
    PAGELET_DEFAULT_IDEMPOTENCY_TTL_MS,
    PAGELET_ELIGIBLE_VIEW_TYPE,
    PAGELET_FOCUS_LATEST_COMMAND_ID,
    PAGELET_FOCUS_LATEST_DEFAULT_HOTKEY,
    PAGELET_FOCUSABLE_SELECTORS,
    PAGELET_OPEN_PANEL_COMMAND_ID,
    PAGELET_RIBBON_CSS_CLASS,
    PAGELET_RIBBON_DEFAULT_TOOLTIP,
    PAGELET_RIBBON_ICON_ID,
    PAGELET_REVIEW_CURRENT_COMMAND_ID,
    PAGELET_SUGGESTION_CARD_CLASS,
    PageletCoalescerClearedError,
    PageletReviewCoalescer,
    findFirstFocusableInCard,
    findFirstSuggestionCard,
    findFocusTargetForCommand,
    getActiveMarkdownView,
    isPageletEligibleView,
    registerPageletFocusCommand,
    registerPageletOpenPanelCommand,
    registerPageletReviewCurrentCommand,
    registerPageletRibbonIcon,
    type PageletCoalescerEntrySnapshot,
    type PageletCoalescerOptions,
    type PageletCommandDefinition,
    type PageletCommandHost,
    type PageletFocusableElement,
    type PageletHotkey,
    type PageletQueryRoot,
    type PageletReviewKey,
    type PageletRibbonElement,
    type PageletRibbonHost,
    type PageletViewTypeProbe,
    type PageletWorkspaceLike,
    type RegisterPageletFocusCommandOptions,
    type RegisterPageletOpenPanelCommandOptions,
    type RegisterPageletReviewCurrentCommandOptions,
    type RegisterPageletRibbonOptions,
    type RegisterPageletRibbonResult,
} from "./compat";
