import { afterEach, describe, expect, it } from "@jest/globals";
import { execFileSync } from "node:child_process";
import {
    existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, symlinkSync, writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { pathToFileURL } from "node:url";

const assets = ["main.js", "styles.css", "manifest.json", "manifest-beta.json"];
const obsolete = ["vss-sqlite-worker.js", "sqlite3.wasm"];
const provenance = "dist/fts-ios-production-build-provenance.json";
const deployModule = pathToFileURL(join(process.cwd(), "scripts/deploy-current.mjs")).href;
const artifactModule = pathToFileURL(join(process.cwd(), "scripts/lib/fts-ios-runtime-artifact.mjs")).href;
const temporaryRoots: string[] = [];

afterEach(() => {
    for (const root of temporaryRoots.splice(0)) rmSync(root, { recursive: true, force: true });
});

function node(source: string): string {
    return execFileSync(process.execPath, ["--input-type=module", "-e", source], { encoding: "utf8" });
}

function write(root: string, path: string, contents: string): void {
    mkdirSync(dirname(join(root, path)), { recursive: true });
    writeFileSync(join(root, path), contents);
}

function fixture(): string {
    const root = mkdtempSync(join(tmpdir(), "pa-deploy-current-"));
    temporaryRoots.push(root);
    for (const path of [
        "src/main.ts", "skills/example/SKILL.md", "licenses/example.txt",
        "esbuild.config.mjs", "package.json", "package-lock.json", "tsconfig.json",
        "manifest.json", "manifest-beta.json", "styles.css", "tailwind.config.cjs",
        "scripts/lib/fts-ios-runtime-artifact.mjs", "scripts/lib/fts-ios-runtime-bundle.mjs",
        "scripts/lib/fts-ios-runtime-session.mjs",
    ]) write(root, path, `${path}\n`);
    write(root, "package.json", '{"name":"personal-assistant","version":"2.9.2"}\n');
    write(root, "manifest.json", '{"id":"personal-assistant","version":"2.9.2"}\n');
    write(root, "manifest-beta.json", '{"id":"personal-assistant","version":"2.9.2-beta.1"}\n');
    const main = "/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD\n"
        + "getLoadedPluginBuildIdentity plugin-onload-cached-main-js\n"
        + ".".repeat(256 * 1024) + " */\n";
    write(root, "dist/main.js", main);
    for (const name of assets.slice(1)) write(root, `dist/${name}`, readFileSync(join(root, name), "utf8"));
    node(`import { writeFtsIosLocalProductionBuildProvenance } from ${JSON.stringify(artifactModule)};
        await writeFtsIosLocalProductionBuildProvenance({ repositoryRoot: ${JSON.stringify(root)} });`);
    return root;
}

function seedDestination(root: string): string {
    const destination = join(root, "test vault", ".obsidian", "plugins", "personal-assistant");
    for (const name of [...assets, ...obsolete, "data.json", "other.txt"]) {
        write(destination, name, `previous ${name}\n`);
    }
    return destination;
}

function deploy(root: string, destinations: string[]): Array<{ error?: string; assets?: string[] }> {
    return JSON.parse(node(`import { deployCurrent } from ${JSON.stringify(deployModule)};
        const results = [];
        for (const destination of ${JSON.stringify(destinations)}) {
            try { results.push(await deployCurrent({ repositoryRoot: ${JSON.stringify(root)}, destination })); }
            catch (error) { results.push({ error: error.message }); }
        }
        console.log(JSON.stringify(results));`));
}

describe("scripts/deploy-current.mjs", () => {
    it("copies the four verified assets, removes obsolete assets, and preserves settings and other files", () => {
        const root = fixture();
        const destination = seedDestination(root);
        expect(deploy(root, [destination])[0].assets).toEqual(assets);
        for (const name of assets) expect(readFileSync(join(destination, name))).toEqual(readFileSync(join(root, "dist", name)));
        for (const name of obsolete) expect(existsSync(join(destination, name))).toBe(false);
        for (const name of ["data.json", "other.txt"]) {
            expect(readFileSync(join(destination, name), "utf8")).toBe(`previous ${name}\n`);
        }
    });

    it("creates a missing destination only after validation succeeds", () => {
        const root = fixture();
        const destination = join(root, "new vault", "plugin");
        expect(deploy(root, [destination])[0].assets).toEqual(assets);
        for (const name of assets) expect(readFileSync(join(destination, name))).toEqual(readFileSync(join(root, "dist", name)));
    });

    const invalidInputs: Array<[string, (root: string) => void, string]> = [
        ["missing provenance", (root) => rmSync(join(root, provenance)), "provenance_missing"],
        ["invalid provenance JSON", (root) => write(root, provenance, "{"), "provenance_invalid"],
        ["corrupt provenance", (root) => {
            const receipt = JSON.parse(readFileSync(join(root, provenance), "utf8"));
            receipt.provenancePayloadSha256 = "0".repeat(64);
            write(root, provenance, JSON.stringify(receipt));
        }, "provenance_integrity_invalid"],
        ["changed main", (root) => write(root, "dist/main.js", readFileSync(join(root, "dist/main.js"), "utf8") + "// changed\n"), "provenance_artifact_mismatch"],
        ["missing main", (root) => rmSync(join(root, "dist/main.js")), "ENOENT"],
        ...["src/main.ts", "package.json", "manifest.json"].map((path): [string, (root: string) => void, string] => [
            `changed source ${path}`, (root) => write(root, path, `${path} changed\n`), "current_plugin_artifact_stale",
        ]),
        ...assets.slice(1).flatMap((name): Array<[string, (root: string) => void, string]> => [
            [`mismatched ${name}`, (root) => write(root, `dist/${name}`, "different\n"), `dist/${name} does not match`],
            [`missing ${name}`, (root) => rmSync(join(root, "dist", name)), "ENOENT"],
        ]),
    ];

    it.each(invalidInputs)("rejects %s before changing or creating a destination", (_name, mutate, expected) => {
        const root = fixture();
        const existing = seedDestination(root);
        const missing = join(root, "missing destination");
        mutate(root);
        for (const result of deploy(root, [existing, missing])) expect(result.error).toContain(expected);
        expect(existsSync(missing)).toBe(false);
        for (const name of [...assets, ...obsolete, "data.json", "other.txt"]) {
            expect(readFileSync(join(existing, name), "utf8")).toBe(`previous ${name}\n`);
        }
    });

    it("rejects source and dist destinations, including a symlink alias", () => {
        const root = fixture();
        const alias = join(root, "dist alias");
        symlinkSync(join(root, "dist"), alias);
        const before = readFileSync(join(root, "dist/main.js"));
        const destinations = [root, join(root, "dist"), join(root, "src/new"), alias];
        for (const result of deploy(root, destinations)) expect(result.error).toContain("must not overwrite");
        expect(readFileSync(join(root, "dist/main.js"))).toEqual(before);
        expect(existsSync(join(root, "src/new"))).toBe(false);
    });

    it("rejects symlink assets before writing any other asset", () => {
        const root = fixture();
        const destination = seedDestination(root);
        rmSync(join(destination, "styles.css"));
        symlinkSync(join(root, "styles.css"), join(destination, "styles.css"));
        expect(deploy(root, [destination])[0].error).toContain("regular file");
        expect(readFileSync(join(destination, "main.js"), "utf8")).toBe("previous main.js\n");
        expect(readFileSync(join(root, "styles.css"), "utf8")).toBe("styles.css\n");
        for (const name of obsolete) expect(existsSync(join(destination, name))).toBe(true);
    });
});
